name: ci

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:

    name: Build
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable

    - name: Install components
      run: rustup component add --toolchain stable rustfmt clippy

    - name: Fetch
      uses: actions-rs/cargo@v1
      with:
        command: fetch

    - name: Check
      env:
        CARGO_INCREMENTAL: 0
      uses: actions-rs/cargo@v1
      with:
        command: check

    - name: Format
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        arguments: --all -- --check

    - name: Clippy
      uses: actions-rs/cargo@v1
      env:
        CARGO_INCREMENTAL: 0
      with:
        command: clippy
        arguments: -- -D warnings

    - name: Test
      uses: actions-rs/cargo@v1
      env:
        CARGO_INCREMENTAL: 0
      with:
        command: test
